networks:
  tunnel:
    external: true

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ORIGIN=https://fantasy.imullett.com
      - PUBLIC_API_URL=http://localhost:5000
      - PRIVATE_API_URL=http://flask:5000
    depends_on:
      - flask
    networks:
      - tunnel

  flask:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./secrets:/app/secrets
    networks:
      - tunnel

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: memesbowl123
      MARIADB_USER: ingestor
      MARIADB_PASSWORD: memesbowl123
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3 
    networks:
      - tunnel
